### ISSUE TITLE
Radial speed profile

### ISSUE THREAD

**Issue by Ashwita2619** [AntSimi/py-eddy-tracker#81]
Hello Antoine,

Could you please explain what is the definition of 'uavg_profile'?

**Comment by AntSimi** [comment]
Hi,
This is the mean of speed along each contour contain in one eddy, which will be interpolated on a fixed size array.
I add a section in this [example](https://py-eddy-tracker.readthedocs.io/en/latest/python_module/01_general_things/pet_storage.html#speed-profile-storage) in order to give more information about it.

**Comment by Ashwita2619** [comment]
thanks…
