### ISSUE TITLE
surface detection

### ISSUE THREAD

**Issue by loic23physics** [AntSimi/py-eddy-tracker#99]
Hi,

I'm running the code for surface detections using zeta variable, and I see that for a detected eddy, in this case a NBC ring, the contour size fluctuates a lot between the time steps. I checked this using a code to map SSH contours, and overlaying the detected contours. The parameters used here were : z_max = 0.5 m, z_min = -0.5 m and step = 0.0001. If I try a bigger step it will not detected the ring at all for a certain percentage of the timesteps, whereas if I make it smaller it doesn't improve the detection any further. I have tried with a range of zeta values from (0.1,-0.1) to (3,3), without success, as well as changing the error shape bounds.

Would you have an idea how this could be solved ?

Thanks,

Loïc
![teststep_2007-08-01-00](https://user-images.githubusercontent.com/87391344/125511904-c8141daa-9f86-42d3-bf13-0c5adfe61c2b.png)
![teststep_2007-08-01-12](https://user-images.githubusercontent.com/87391344/125511926-b9ead326-0533-47e5-8f51-8d324c1a3f51.png)

**Comment by AntSimi** [comment]
Could you explain how you run detection?

**Comment by loic23physics** [comment]
[detection_gigatl6 (1).txt](https://github.com/AntSimi/py-eddy-tracker/files/6816165/detection_gigatl6.1.txt)
The detection is run using this code. It works with a 1h time step simulation, and uses the parameters set in identification section

**Comment by AntSimi** [comment]
Firstly, i never work with other field than SLA(Sea Level Anomalie) or ADT(Absolute Dynamic Topography) for eddy detection.
Also, i think also you used a modified version of py-eddy-tracker because in the orginal one you can't set `zmin` and `zmax` for eddy detection.

But i imagine your problem come from some noisy values which stop contour collecting:

-  First solution could be to apply a filtering step before eddy detection, to remove this high frequency signal which stop the contour collecting
- Second solution, add some code to allow very small local extremum in eddies

**Comment by evanmason** [comment]
As I see it the code is working, but there is a large disparity in the detected areas of the ring between your two subplots. This will mean you have a very small `speed_radius` in the bottom subplot, and this is unlikely given that NBC rings are large.

The easy fix is to do some post-processing of your tracks using the Loess filter (available from ` py_eddy_tracker.observations.tracking import TrackEddiesObservations`) on your `speed_radius` and other variables as necessary. 

See `https://py-eddy-tracker.readthedocs.io/en/stable/_autosummary/py_eddy_tracker.observations.tracking.track_loess_filter.html?highlight=loess`

**Comment by Mesharou** [comment]
Hi guys,

Thanks for the very quick answer! Loic is working with us at LOPS and using a code we slightly modified (https://github.com/Mesharou/py-eddy-tracker). What we call 'zeta'  is in fact ADT. 

Here I believe the problem is due to multiple extrema inside the ring. So just using a higher value for 'mle' seems to solve the issue. Note that filtering small scales does the trick too:

![download-1](https://user-images.githubusercontent.com/8410929/125842948-54bac1da-9b9d-4473-992e-6c675e4c9a55.png)

Cheers,
Jonathan

**Comment by AntSimi** [comment]
Bottom right subplot have some contours smaller than top left subplot. Did you do more changes than 'mle'?

**Comment by Mesharou** [comment]
Indeed, the shape_error has also been reduced for the experiment in the bottom right panel.

Here is what you get if you change only mle:

![download-2](https://user-images.githubusercontent.com/8410929/125860179-6919ebba-25f9-43f6-9733-30fee4907056.png)
